package sit.sitcom.model;
// Generated Dec 27, 2017 2:28:30 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductCode generated by hbm2java
 */
@Entity
@Table(name="PRODUCT_CODE"
    ,schema="APP"
)
public class ProductCode  implements java.io.Serializable {


     private String prodCode;
     private char discountCode;
     private String description;

    public ProductCode() {
    }

	
    public ProductCode(String prodCode, char discountCode) {
        this.prodCode = prodCode;
        this.discountCode = discountCode;
    }
    public ProductCode(String prodCode, char discountCode, String description) {
       this.prodCode = prodCode;
       this.discountCode = discountCode;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="PROD_CODE", unique=true, nullable=false, length=2)
    public String getProdCode() {
        return this.prodCode;
    }
    
    public void setProdCode(String prodCode) {
        this.prodCode = prodCode;
    }

    
    @Column(name="DISCOUNT_CODE", nullable=false, length=1)
    public char getDiscountCode() {
        return this.discountCode;
    }
    
    public void setDiscountCode(char discountCode) {
        this.discountCode = discountCode;
    }

    
    @Column(name="DESCRIPTION", length=10)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


