package sit.sitcom.model;
// Generated Dec 27, 2017 2:28:30 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchaseOrder generated by hbm2java
 */
@Entity
@Table(name="PURCHASE_ORDER"
    ,schema="APP"
)
public class PurchaseOrder  implements java.io.Serializable {


     private int orderNum;
     private int customerId;
     private int productId;
     private Short quantity;
     private BigDecimal shippingCost;
     private Date salesDate;
     private Date shippingDate;
     private String freightCompany;

    public PurchaseOrder() {
    }

	
    public PurchaseOrder(int orderNum, int customerId, int productId) {
        this.orderNum = orderNum;
        this.customerId = customerId;
        this.productId = productId;
    }
    public PurchaseOrder(int orderNum, int customerId, int productId, Short quantity, BigDecimal shippingCost, Date salesDate, Date shippingDate, String freightCompany) {
       this.orderNum = orderNum;
       this.customerId = customerId;
       this.productId = productId;
       this.quantity = quantity;
       this.shippingCost = shippingCost;
       this.salesDate = salesDate;
       this.shippingDate = shippingDate;
       this.freightCompany = freightCompany;
    }
   
     @Id 

    
    @Column(name="ORDER_NUM", unique=true, nullable=false)
    public int getOrderNum() {
        return this.orderNum;
    }
    
    public void setOrderNum(int orderNum) {
        this.orderNum = orderNum;
    }

    
    @Column(name="CUSTOMER_ID", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="PRODUCT_ID", nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }

    
    @Column(name="QUANTITY")
    public Short getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Short quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="SHIPPING_COST", precision=12)
    public BigDecimal getShippingCost() {
        return this.shippingCost;
    }
    
    public void setShippingCost(BigDecimal shippingCost) {
        this.shippingCost = shippingCost;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SALES_DATE", length=10)
    public Date getSalesDate() {
        return this.salesDate;
    }
    
    public void setSalesDate(Date salesDate) {
        this.salesDate = salesDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SHIPPING_DATE", length=10)
    public Date getShippingDate() {
        return this.shippingDate;
    }
    
    public void setShippingDate(Date shippingDate) {
        this.shippingDate = shippingDate;
    }

    
    @Column(name="FREIGHT_COMPANY", length=30)
    public String getFreightCompany() {
        return this.freightCompany;
    }
    
    public void setFreightCompany(String freightCompany) {
        this.freightCompany = freightCompany;
    }




}


